In [3]:
# svm loan approver
from path import Path
import numpy as np
import pandas as pd

df = pd.read_csv('./Resources/loans.csv')
df.head()

     assets  liabilities    income  credit_score  mortgage   status
0  0.210859     0.452865  0.281367      0.628039  0.302682     deny
1  0.395018     0.661153  0.330622      0.638439  0.502831  approve
2  0.291186     0.593432  0.438436      0.434863  0.315574  approve
3  0.458640     0.576156  0.744167      0.291324  0.394891  approve
4  0.463470     0.292414  0.489887      0.811384  0.566605  approve

In [4]:
# Separate the features X from target y
y = df["status"]
X = df.drop(columns="status")

In [5]:
X

      assets  liabilities    income  credit_score  mortgage
0   0.210859     0.452865  0.281367      0.628039  0.302682
1   0.395018     0.661153  0.330622      0.638439  0.502831
2   0.291186     0.593432  0.438436      0.434863  0.315574
3   0.458640     0.576156  0.744167      0.291324  0.394891
4   0.463470     0.292414  0.489887      0.811384  0.566605
5   0.201576     0.333237  0.518700      0.426101  0.187398
6   0.491437     0.610539  0.499648      0.594682  0.557456
7   0.270549     0.414655  0.461616      0.516732  0.299642
8   0.305833     0.252547  0.677386      0.426792  0.261975
9   0.375657     0.292947  0.665386      0.496027  0.358359
10  0.460347     0.400883  0.560078      0.642953  0.512708
11  0.563920     0.341523  0.735423      0.607063  0.575166
12  0.522539     0.561265  0.621610      0.525626  0.545797
13  0.459907     0.339288  0.657480      0.573607  0.471696
14  0.465152     0.258396  0.505571      0.820498  0.565636
15  0.419243     0.562311  0.538371      0.496841  0.445517
16  0.159373     0.588234  0.443050      0.272009  0.133107
17  0.807383     0.547117  0.778485      0.699386  0.860140
18  0.601576     0.502359  0.744867      0.520951  0.600554
19  0.244618     0.307837  0.466980      0.559035  0.275701
20  0.215248     0.210288  0.518871      0.535147  0.222552
21  0.368954     0.365910  0.570736      0.544824  0.386673
22  0.402361     0.651075  0.657715      0.268287  0.350825
23  0.157904     0.499608  0.323652      0.478066  0.202629
24  0.461662     0.452089  0.573054      0.590689  0.501165
25  0.442577     0.427651  0.473539      0.703379  0.527979
26  0.191939     0.439143  0.352387      0.531244  0.243076
27  0.452024     0.469880  0.580314      0.556923  0.481929
28  0.188005     0.528004  0.000000      0.876190  0.401838
29  0.819125     0.455026  0.974529      0.551271  0.790642
..       ...          ...       ...           ...       ...
70  0.000000     0.042944  0.418096      0.516804  0.000000
71  0.480811     0.738489  0.696462      0.252703  0.427386
72  0.291082     0.639415  0.526486      0.296032  0.265273
73  0.626949     0.503145  0.917948      0.346776  0.548781
74  0.512126     0.568635  0.542369      0.601023  0.570114
75  0.270398     0.369955  0.523497      0.477021  0.274508
76  0.415150     0.586481  0.548308      0.461895  0.431696
77  0.378294     0.540969  0.703998      0.266967  0.309437
78  0.172922     0.850857  0.300861      0.259078  0.187538
79  0.568542     0.293496  0.613209      0.793352  0.649010
80  0.408557     0.756109  0.768878      0.065404  0.289703
81  0.533648     0.350688  0.845587      0.432872  0.477358
82  0.546006     0.431993  0.661720      0.604200  0.575285
83  0.407738     0.343472  0.621159      0.549557  0.417702
84  0.383701     0.329348  0.457082      0.724758  0.468596
85  0.402316     0.445112  0.582394      0.512271  0.416007
86  0.273220     1.000000  0.528884      0.000000  0.191231
87  1.000000     0.649655  1.000000      0.596050  1.000000
88  0.376941     0.562520  0.463880      0.532986  0.424667
89  0.489173     0.298624  0.751505      0.528855  0.470321
90  0.479122     0.318010  0.699995      0.562867  0.479669
91  0.364564     0.610073  0.491389      0.449532  0.387565
92  0.250497     0.324769  0.597616      0.399038  0.216225
93  0.651009     0.408233  0.819707      0.563792  0.643603
94  0.454914     0.295911  0.735232      0.508212  0.431811
95  0.360945     0.823295  0.542451      0.224285  0.328504
96  0.114420     0.107174  0.619564      0.370300  0.047719
97  0.309276     0.692433  0.483730      0.328953  0.304493
98  0.549153     0.301588  0.651869      0.717826  0.602004
99  0.448187     0.217651  0.388670      0.968609  0.606231

[100 rows x 5 columns]

In [7]:
# Split our data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,  random_state=1, stratify=y)
X_train.shape

(75, 5)

In [8]:
# Create a SVM model
# Support vector achine
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [9]:
# Fit (train) or model using the training data
model.fit(X_train, y_train)

SVC(kernel='linear')

In [10]:
# Make a predictions
y_predictions = model.predict(X_test)
results = pd.DataFrame({
   "Prediction": y_predictions,
   "Actual": y_test
}).reset_index(drop=True)
results.head()

  Prediction   Actual
0    approve     deny
1       deny  approve
2       deny     deny
3    approve     deny
4       deny     deny

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predictions)

0.6

In [17]:
# Generate confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predictions)

array([[7, 5],
       [5, 8]])

In [18]:
# Classification Report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predictions))

              precision    recall  f1-score   support

     approve       0.58      0.58      0.58        12
        deny       0.62      0.62      0.62        13

    accuracy                           0.60        25
   macro avg       0.60      0.60      0.60        25
weighted avg       0.60      0.60      0.60        25